import Head from "next/head";
import styles from "../styles/Home.module.css";
import { getArticles } from "../services";
import ArticleCard from "../components/ArticleCard";
import { Box, Container, Grid } from "@mui/material";
import Categories from "../components/Categories";
import RecentArticles from "../components/RecentArticles";

export default function Home({ articles }) {
  console.log(articles);
  return (
    <Box>
      <Head>
        <title>Front-End</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxWidth="lg">
        <Grid container spacing={6}>
          <Grid item xs={12} md={8}>
            {articles.map((article) => (
              <ArticleCard article={article} key={article.cursor} />
            ))}
          </Grid>
          <Grid item xs={12} md={4}>
            <Box sx={{ position: "sticky", top: "40px", mb: 5 }}>
              <RecentArticles />
              <Categories />
            </Box>
          </Grid>
        </Grid>
      </Container>
    </Box>
  );
}

export async function getStaticProps() {
  const articles = (await getArticles()) || [];
  return {
    props: { articles },
  };
}
